feat: `match_name` gains `join_id` col, allowing for an initial matching override based on some unique ID column
RMI-PACTA/r2dii.match pull request #460
Opened 2024-03-07 08:10 UTC by jdhoffa

This ID column could be, for example, `lei` or `isin`. 

Some open questions I have before marking this as ready for review: 

- [x] Currently the ID column must be identical between each dataset, but I think perhaps it might be better to allow for a named argument, with one name indicating the `loanbook` column name (e.g. `lei_direct_loantaker`), and another column indicating the `abcd` column name (e.g. `lei`) 
- [x] Currently the functionality only allows for a SINGLE join column. e.g. there is no way to give a handful of columns, and join by priority (ISIN -> LEI -> etc.)
- [x] Definitely needs way more tests. Especially, there should be some input checks that assess that there aren't multiple joins per company. I can imagine a `loanbook` with multiple identical LEIs, and an `abcd` with several `name_company` values that have the same LEI. Need to consider what to do in that case

See reprex:
``` r
library(tibble)
library(r2dii.match)

loanbook <- tibble(
  sector_classification_system = "NACE",
  sector_classification_direct_loantaker = "100", # this generally shouldn't match to anything
  id_ultimate_parent = c("UP15", "UP16"),
  name_ultimate_parent = c("Foo", "Bar"),
  id_direct_loantaker = c("C294", "C295"),
  name_direct_loantaker = "Yuamen Xinneng Thermal Power Co Ltd",
  lei = c("LEI123", NA_character_)
)

abcd <- tibble(
  name_company = "alpine knits india pvt. limited",
  sector = "power",
  lei = "LEI123"
)

# no match found, as expected
# outputs "message" that no match was found by fuzzy matching, and warning that no match was found overall
match_name(loanbook, abcd, join_id = NULL)
#> Found no match via fuzzy matching.
#> Warning: Found no match.
#> # A tibble: 0 × 16
#> # ℹ 16 variables: sector_classification_system <chr>,
#> #   sector_classification_direct_loantaker <chr>, id_ultimate_parent <chr>,
#> #   name_ultimate_parent <chr>, id_direct_loantaker <chr>,
#> #   name_direct_loantaker <chr>, lei <chr>, id_2dii <lgl>, level <lgl>,
#> #   sector <lgl>, sector_abcd <lgl>, name <lgl>, name_abcd <lgl>, score <lgl>,
#> #   source <lgl>, borderline <lgl>

# no match found via fuzzy matching, as expected
# outputs "message" that no match was found by fuzzy matching, but successfully outputs the joined match
match_name(loanbook, abcd, join_id = "lei")
#> Found no match via fuzzy matching.
#> # A tibble: 1 × 10
#>   sector_classification_system sector_classification_direct…¹ id_ultimate_parent
#>   <chr>                        <chr>                          <chr>             
#> 1 NACE                         100                            UP15              
#> # ℹ abbreviated name: ¹​sector_classification_direct_loantaker
#> # ℹ 7 more variables: name_ultimate_parent <chr>, id_direct_loantaker <chr>,
#> #   name_direct_loantaker <chr>, name <chr>, sector <chr>, alias <chr>,
#> #   score <dbl>
```

<sup>Created on 2024-03-07 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Closes #135

2024-03-07 08:11 UTC, jdhoffa commented
@jacobvjk requesting your review here for some input already

2024-03-07 08:36 UTC, cjyetman commented
Allowing a named character vector, e.g. `join_id = c(lei_direct_loantaker = "lei")`, might be an easy way to facilitate naming different columns in the loanbook and abcd datasets.

2024-03-07 08:55 UTC, jdhoffa commented
I think may make sense to only allow a single join column for now. 
Adding multiple requires some join priority logic, and I'd rather not introduce that complexity yet.
Could be a future feature once this one is in the wild, and proven to not be buggy

2024-03-07 15:22 UTC, jacobvjk reviewed
particularly unclear about removing the `join_id` after the `inner_join` and before the `filter`.
the rest seems quite reasonable

2024-03-07 15:22 UTC, jacobvjk commented on R/match_name.R
> +      !!join_id := NULL,
I am not sure I understand why we are doing this. In my understanding, `join_matched` will at this point contain only loans to companies that were joined by `join_id`. Now we are removing the `join_id` column from `join_matched`. What does the `filter` below do, if we remove `join_id` here? Stepping through the test line by line it seemed like nothing is filtered. `loanbook` still contains the loan that was already matched via the `join_id`

2024-03-07 15:43 UTC, jdhoffa commented on R/restructure_abcd.R
> +    out <- dplyr::transmute(
Don't mind changing it here!
`transmute()` was a shoe-in from a very long time ago

2024-03-07 15:45 UTC, jdhoffa commented on R/restructure_abcd.R
> +    out <- dplyr::transmute(
https://github.com/RMI-PACTA/r2dii.match/issues/461

2024-03-07 15:47 UTC, jdhoffa commented on R/match_name.R
> +      !!join_id := NULL,
@jacobvjk do you think that, if `join_id != NULL`, that it would make sense to have the `join_id` column present in the final output?

2024-03-07 15:59 UTC, jacobvjk commented on R/match_name.R
> +      !!join_id := NULL,
Yes, I think there are definitely cases, where users would prefer to be able to report the share of loans they matched using the `join_id` versus name matching. So I would suggest keeping it if that is an easy thing to do

2024-03-07 16:07 UTC, jdhoffa commented
So there's a bunch of failing checks that I will look into later (I have a feeling it's because of changes in `r2dii.data` messing up our vignettes etc.)

But the core functionality seems to be there :-)

2024-03-12 10:04 UTC, jdhoffa commented
This seems to function now as expected, with `dplyr::*_join`-like syntax. 
See reprex below: 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(r2dii.data)
library(r2dii.match)

# 441 points to the company Russo, Russo e Russo Group
abcd_demo <- dplyr::mutate(
  abcd_demo, 
  lei = dplyr::case_when(
    company_id == "441" ~ "LEI123",
    TRUE ~ lei
  )
)

# C267 points to the company Russo s.r.l.
loanbook_demo <- dplyr::mutate(
  loanbook_demo, 
  lei_direct_loantaker = dplyr::case_when(
    id_direct_loantaker == "C267" ~ "LEI123",
    TRUE ~ lei_direct_loantaker
  )
)

out <- match_name(
  loanbook_demo, 
  abcd_demo, 
  join_id = c(lei_direct_loantaker = "lei")
)

prioritized <- prioritize(out)

prioritized |> 
  filter(id_direct_loantaker == "C267") |> 
  select(id_direct_loantaker, lei_direct_loantaker, level, source, score, name, name_abcd)
#> # A tibble: 1 × 7
#>   id_direct_loantaker lei_direct_loantaker level    source score name  name_abcd
#>   <chr>               <chr>                <chr>    <chr>  <dbl> <chr> <chr>    
#> 1 C267                LEI123               lei_dir… id jo…     1 Russ… Russo, R…
```

<sup>Created on 2024-03-12 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

2024-03-12 15:54 UTC, jdhoffa commented
@cjyetman I've tagged you as a reviewer, understanding you may not have enough context to get exactly what is going on here (that's what @jacobvjk is there for), but I would appreciate a second pair of eyes on this 😊

2024-03-12 16:10 UTC, cjyetman commented on R/match_name.R
> +#' @param join_id A join specification passe to [dplyr::inner_join()]. If a
```suggestion
#' @param join_id A join specification passed to [dplyr::inner_join()]. If a
```

2024-03-12 16:20 UTC, cjyetman submitted a review, later dismissed
makes sense to me

2024-03-12 17:54 UTC, jacobvjk reviewed
None of the comments are show stoppers, but I would like to hear your thoughts before I approve. I think the error messages are a bit confusing.

2024-03-12 17:54 UTC, jacobvjk commented on tests/testthat/test-match_name.R
> +    join_id = c(lei_direct_loantaker = "lei")
this is a named vector, not a list. the test suggests that a list will be passed

2024-03-12 17:54 UTC, jacobvjk commented on tests/testthat/test-match_name.R
> +  # with `join_id` as named list
this is a named vector not a list. It does not actually work with `join_id = list(foo_lbk = "foo_abcd")`

2024-03-12 17:54 UTC, jacobvjk commented on R/match_name.R
> +        "The join_id `{join_id}` must be present in both `loanbook` and `abcd`. It's not present in `loanbook`."
A join object is created that allows differently named columns for the `join_id`. The error message implies that the name of the `join_id` column must be the same in both `loanbook` and `abcd`

2024-03-12 17:54 UTC, jacobvjk commented on R/match_name.R
> +        "The join_id `{join_id}` must be present in both `loanbook` and `abcd`. It's not present in `abcd`."
A join object is created that allows differently named columns for the `join_id`. The error message implies that the name of the `join_id` column must be the same in both `loanbook` and `abcd`

2024-03-12 17:54 UTC, jacobvjk commented on tests/testthat/test-match_name.R
> +    join_id = c(lei_direct_loantaker = "lei")
see above

2024-03-14 11:12 UTC, jacobvjk requested changes
still two instances mentioning list inputs

2024-03-14 11:12 UTC, jacobvjk commented on R/match_name.R
> +#'   `abcd`. If a named list, uses the name as the join column of `loanbook` and
```suggestion
#'   `abcd`. If a named character vector, it uses the name as the join column of `loanbook` and
```

2024-03-14 11:12 UTC, jacobvjk commented on tests/testthat/test-match_name.R
> +test_that("with `join_id` accepts list input indicating different cols (#135)", {
```suggestion
test_that("with `join_id` accepts named character vector input indicating different cols (#135)", {
```

2024-03-14 11:24 UTC, jacobvjk approved these changes
lgtm

2024-03-14 11:27 UTC, merged