Add common R action
RMI-PACTA/r2dii.match pull request #480
Opened 2024-06-04 15:46 UTC by AlexAxthelm

2024-06-05 07:10 UTC, cjyetman commented
probably doesn't make sense to add this without removing the existing R CMD checks

2024-06-06 11:15 UTC, jdhoffa requested changes

2024-06-06 11:15 UTC, jdhoffa commented on .github/workflows/R.yml
> +    uses: RMI-PACTA/actions/.github/workflows/R-CMD-check.yml@add-extra-repos-to-rcmdcheck
This action still depends on a PR branch, please merge that branch first

2024-06-06 11:16 UTC, jdhoffa commented
Depends on https://github.com/RMI-PACTA/actions/pull/90

2024-06-07 08:06 UTC, jdhoffa requested changes

2024-06-07 08:06 UTC, jdhoffa commented on R/prioritize.R
> +#' ```
Please move this change (and the other content/ not action related file commits) to a separate PR (to keep this PR focused on changing only the workflow files)

2024-06-07 09:35 UTC, AlexAxthelm commented on R/prioritize.R
> +#' ```
https://github.com/RMI-PACTA/r2dii.match/pull/483

2024-06-10 08:24 UTC, AlexAxthelm commented
Note that with this PR, we're testing the HEAD (latest version of `main` or PR) against both the CRAN and latest `main` versions of all dependencies.

Note that when we are testing against the dev versions of the dependencies, it is for the RMI-PACTA packages only (for example, `dplyr` is still the CRAN version).

2024-06-10 10:25 UTC, AlexAxthelm commented
@jdhoffa I believe the requested changes were made in #483

2024-06-11 09:28 UTC, jacobvjk approved these changes

2024-06-11 10:00 UTC, jdhoffa approved these changes
lgtm!

2024-06-11 10:00 UTC, merged